### ISSUE TITLE
Latest armory on git not showing chess pieces in html, just board. Krom fails.

### ISSUE THREAD

**Issue by f-rank** [armory3d/chess_example#1]
Board looks empty on html but it does run on the browser, on krom it throws:
ERROR: D:\WORK\chess_example-master\build_chess\compiled\Shaders\deferred_light_quad.frag.glsl:147: 'voxels' : undeclared identifier
ERROR: D:\WORK\chess_example-master\build_chess\compiled\Shaders\deferred_light_quad.frag.glsl:147: '' : missing #endif
ERROR: D:\chess_example-master\build_chess\compiled\Shaders\deferred_light_quad.frag.glsl:147: '' : compilation terminated
ERROR: 3 compilation errors.  No code generated.

SPIR-V is not generated for failed compile or link

**Comment by f-rank** [comment]
Actually, the pieces are there in the html version. But you can only see them from within other pieces, if you look from outside the space of a piece, you see nothing.
Here's the view from inside one piece.
![image](https://user-images.githubusercontent.com/1836566/35956060-426023e0-0c8b-11e8-8298-cc805d398983.png)
krom still throwing the same error as in first post.

**Comment by luboslenco** [comment]
Ah, fixed Krom compilation in https://github.com/armory3d/armory/commit/8632f60fa02bc22d0e50094f5d200ef1a8b658a4. The pieces are invisible in browser because material opacity was set to 0.001. (Opacity affects voxel refract, the values need tweaking..)

**Comment by f-rank** [comment]
Actually a cool effect, the ghosting of the 3D chess pieces :)
